os: windows
language: csharp
mono: none
env:
  - VERSION_PREFIX="0.12.0" VERSION_SUFFIX="alpha"
script:
  - choco install dotnetcore-sdk --pre -y
  - choco install netfx-4.8-devpack --pre -y --ignore-package-exit-codes
  - dotnet restore
  - choco install opencover.portable -y
  - OpenCover.Console.exe -register -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full ./Party.Shared.Tests/Party.Shared.Tests.csproj" -filter:"+[Party*]* -[Party.Shared.Tests*]*" -output:"coverage.xml" -skipautoprops -returntargetcode
  - choco install codecov -y
  - powershell "codecov -f coverage.xml -t $env:CODECOV_TOKEN"
  - powershell "dotnet publish Party.CLI -c Release /p:VersionPrefix=$VERSION_PREFIX.$TRAVIS_BUILD_NUMBER /p:VersionSuffix=$VERSION_SUFFIX"
  - powershell "dotnet pack Party.Shared -c Release /p:VersionPrefix=$VERSION_PREFIX.$TRAVIS_BUILD_NUMBER /p:VersionSuffix=$VERSION_SUFFIX"
  # - powershell "dotnet publish Party.CLI -c Release -r win-x64 /p:VersionPrefix=$VERSION_PREFIX.$TRAVIS_BUILD_NUMBER /p:VersionSuffix=$VERSION_SUFFIX"
  - powershell "mv ./Party.CLI/bin/Release/net48/publish ./Party.CLI/bin/Release/net48/Party"
  - choco install 7zip -y
  - powershell "7z a ./Party.CLI/bin/Release/net48/party-$VERSION_PREFIX.$TRAVIS_BUILD_NUMBER-$VERSION_SUFFIX.zip ./Party.CLI/bin/Release/net48/Party"
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key: $GITHUB_TOKEN
  file:
    # - ./Party.CLI/bin/Release/netcoreapp3.0/win-x64/native/party.exe
    - ./Party.CLI/bin/Release/net48/party-${VERSION_PREFIX}.${TRAVIS_BUILD_NUMBER}-${VERSION_SUFFIX}.zip
    - ./Party.Shared/bin/Release/Party.Shared.${VERSION_PREFIX}.${TRAVIS_BUILD_NUMBER}-${VERSION_SUFFIX}.nupkg
  on:
    tags: true
