os: windows
language: csharp
mono: none
script:
  - choco install dotnetcore-sdk --pre -y
  - dotnet tool install -g coveralls.net
  - dotnet restore Party.Shared.Tests
  - dotnet test Party.Shared.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - csmacnz.coveralls --opencover -i ./Party.Shared.Tests/coverage.opencover.xml --useRelativePaths
  - dotnet restore Party.CLI
  - dotnet publish Party.CLI -c Release -r win-x64
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key: $GITHUB_TOKEN
  file:
    - ./Party.CLI/bin/Release/netcoreapp3.0/win-x64/native/party.exe
  on:
    tags: true